name: "create README"
description: "Concatenate files and convert YAML blocks to HTML representation."
inputs:
  beforeTOC:
    description: A markdown string between the title and the TOC.
    required: false
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
